# Generated by Django 5.1.5 on 2025-02-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_comment_likes_alter_thread_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='flag',
            field=models.CharField(choices=[('d', 'default'), ('c', 'closed'), ('s', 'sticky'), ('n', 'new')], default=('n', 'new'), max_length=20),
        ),
    ]
