# Generated by Django 5.1.5 on 2025-02-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_thread_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='flag',
            field=models.CharField(choices=[('d', 'default'), ('c', 'closed'), ('p', 'pinned'), ('n', 'new')], default=('n', 'new'), max_length=20),
        ),
    ]
